const types = {
  SAVE_UID: 'SAVE_UID',
  GET_LIST_CLIENTS: 'GET_LIST_CLIENTS',
  GET_LIST_CLIENTS_SUCCESS: 'GET_LIST_CLIENTS_SUCCESS',
  GET_LIST_CLIENTS_ERROR: 'GET_LIST_CLIENTS_ERROR',
  GET_LIST_APOLICES: 'GET_LIST_APOLICES',
  GET_LIST_APOLICES_SUCCESS: 'GET_LIST_APOLICES_SUCCESS',
  GET_LIST_APOLICES_ERROR: 'GET_LIST_APOLICES_ERROR',
  SELECT_CLIENT: 'SELECT_CLIENT',
  SELECT_APOLICE: 'SELECT_APOLICE',
  GET_LIST_TASKS: 'GET_LIST_TASKS',
  GET_LIST_TASKS_SUCCESS: 'GET_LIST_TASKS_SUCCESS',
  GET_LIST_TASKS_ERROR: 'GET_LIST_TASKS_ERROR'
}

export default types;